services:
  nlweb:
    image: nlweb:prod
    env_file: .env
    restart: unless-stopped
    ports:
      - "127.0.0.1:7015:8000"   # host 7001 -> container 8000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      DATABASE_URL: "postgresql://rag:ragpass@host.docker.internal:5432/ragdb?sslmode=disable"
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import socket,sys; s=socket.socket(); s.settimeout(2); s.connect(('127.0.0.1',8000)); sys.exit(0)\""]
      interval: 15s
      timeout: 5s
      retries: 8
      start_period: 20s



