export default defineAppConfig({
  shadcnDocs: {
    site: {
      name: 'Knowledge Centre',
      description: 'ESW Docs.',
      ogImage: '/hero.png',
      ogImageComponent: 'ShadcnDocs',
      ogImageColor: 'light',
      umami: {
        enable: true,
        src: 'https://cloud.umami.is/script.js',
        dataWebsiteId: 'd793fbf3-461e-4e26-9ec9-4e9141df96ee',
      },
    },
    theme: {
      customizable: true,
      color: 'teal',
      radius: 0.5,
    },
    banner: {
      enable: false,
      showClose: true,
      content: 'Welcome to **shadcn-docs-nuxt**',
      to: 'https://github.com/ZTL-UwU/shadcn-docs-nuxt',
      target: '_blank',
      border: true,
    },
    header: {
      title: 'Knowledge Centre',
      showTitle: true,
      logo: {
        light: '/logo.svg',
        dark: '/ESW-Logo-Light.svg',
      },
      darkModeToggle: true,
      languageSwitcher: {
        enable: false,
        triggerType: 'icon',
        dropdownType: 'select',
      },
      nav: [{
        title: 'Docs',
        links: [{
          title: 'Getting Started',
          to: '/getting-started',
          description: 'Install the ESW Shopify Apps.',
          icon: 'lucide:rocket',
        }, {
          title: 'Integration',
          to: '/integration',
          description: 'Integrate Shopify with ESW services',
          icon: 'lucide:plug',
        }],
      }, {
        title: 'Blog',
        to: '/blog',
        target: '_self',
        showLinkIcon: false,
      }],
      links: [
        {
          icon: 'lucide:login-in',
          to: 'https://security-sts.test.eshopworld.net/Account/Login?ReturnUrl=%2Fconnect%2Fauthorize%2Fcallback%3Fclient_id%3Desw.esp.spa%26redirect_uri%3Dhttps%253A%252F%252Fesp-core-ui.test.eshopworld.net%26response_type%3Dcode%26scope%3Dopenid%2520profile%2520esp.tahoe%2520esp.settings%2520esp.config%2520esp.rob%2520esp.analytics%2520esp.logistics%2520esp.pricing%2520esp.currency%2520esp.country%2520esp.sfs%2520esp.sfs.rec%2520esp.payments%2520esp.declarationsengine%2520esp.configProp%2520esp.fx%2520esp.checkout%2520esp.ruleset%2520esp.pricingadvisor%2520esp.revisions%2520esp.tenantprovisioning%2520esp.ch%2520retailer.brandstyling%2520esp.platform%2520esp.pricingmodels%2520esp.shippingrates%2520esp.logisticsreturns%2520esp.returns%2520esp.promotion%2520esp.logisticsrouting%2520esp.tooling%2520esp.logisticsdte%2520esp.finance%2520esp.catalog%2520esp.invoicing%2520esp.etp%2520esp.order%2520esp.security%2520esp.retailer%2520esp.shopper%2520esp.tradecomp%26nonce%3D960a56700b669faa4f2188ff7844f50636QhKouYn%26state%3Da908421f36968c69e87524b956d54c26d1iTrOwZU%26code_challenge%3D4mpO_enW61qkH3-IXePTipcV9VnYv9OwOJLPATar9yI%26code_challenge_method%3DS256',
          target: '_blank',
        }
      ],
    },
    aside: {
      useLevel: true,
      collapse: false,
      collapseLevel: 1,
      folderStyle: 'default',
    },
    main: {
      breadCrumb: true,
      showTitle: true,
      codeCopyToast: true,
      codeCopyIcon: 'lucide:clipboard',
      editLink: {
        enable: false,
        pattern: 'https://github.com/ZTL-UwU/shadcn-docs-nuxt/edit/main/www/content/:path',
        text: 'Edit this page',
        icon: 'lucide:square-pen',
        placement: ['docsFooter'],
      },
      backToTop: true,
      codeIcon: {
        'package.json': 'vscode-icons:file-type-node',
        'tsconfig.json': 'vscode-icons:file-type-tsconfig',
        '.npmrc': 'vscode-icons:file-type-npm',
        '.editorconfig': 'vscode-icons:file-type-editorconfig',
        '.eslintrc': 'vscode-icons:file-type-eslint',
        '.eslintrc.cjs': 'vscode-icons:file-type-eslint',
        '.eslintignore': 'vscode-icons:file-type-eslint',
        'eslint.config.js': 'vscode-icons:file-type-eslint',
        'eslint.config.mjs': 'vscode-icons:file-type-eslint',
        'eslint.config.cjs': 'vscode-icons:file-type-eslint',
        '.gitignore': 'vscode-icons:file-type-git',
        'yarn.lock': 'vscode-icons:file-type-yarn',
        '.env': 'vscode-icons:file-type-dotenv',
        '.env.example': 'vscode-icons:file-type-dotenv',
        '.vscode/settings.json': 'vscode-icons:file-type-vscode',
        'nuxt': 'vscode-icons:file-type-nuxt',
        '.nuxtrc': 'vscode-icons:file-type-nuxt',
        '.nuxtignore': 'vscode-icons:file-type-nuxt',
        'nuxt.config.js': 'vscode-icons:file-type-nuxt',
        'nuxt.config.ts': 'vscode-icons:file-type-nuxt',
        'nuxt.schema.ts': 'vscode-icons:file-type-nuxt',
        'tailwind.config.js': 'vscode-icons:file-type-tailwind',
        'tailwind.config.ts': 'vscode-icons:file-type-tailwind',
        'vue': 'vscode-icons:file-type-vue',
        'ts': 'vscode-icons:file-type-typescript',
        'tsx': 'vscode-icons:file-type-typescript',
        'mjs': 'vscode-icons:file-type-js',
        'cjs': 'vscode-icons:file-type-js',
        'js': 'vscode-icons:file-type-js',
        'jsx': 'vscode-icons:file-type-js',
        'md': 'vscode-icons:file-type-markdown',
        'mdc': 'vscode-icons:file-type-markdown',
        'css': 'vscode-icons:file-type-css',
        'py': 'vscode-icons:file-type-python',
        'npm': 'vscode-icons:file-type-npm',
        'pnpm': 'vscode-icons:file-type-pnpm',
        'npx': 'vscode-icons:file-type-npm',
        'yarn': 'vscode-icons:file-type-yarn',
        'bun': 'vscode-icons:file-type-bun',
        'yml': 'vscode-icons:file-type-light-yaml',
        'json': 'vscode-icons:file-type-json',
        'terminal': 'lucide:terminal',
      },
    },
    footer: {
      credits: 'FOOTER_CREDIT',
      links: [
        {
          icon: 'lucide:users',
          title: 'About us ',
          to: 'https://esw.com/about-us/',
          target: '_blank',
        },
        {
          icon: 'lucide:package-open',
          title: 'Products & Services',
          to: 'https://esw.com/product-and-services/',
          target: '_blank',
        },
        {
          icon: 'lucide-lab:factory',
          title: 'Industry expertise',
          to: 'https://esw.com/industry-expertise/',
          target: '_blank',
        },
        {
          icon: 'lucide:arrow-right-from-line',
          title: 'Talk to an expert',
          to: 'https://esw.com/talk-to-an-expert/',
          target: '_blank',
        },
        {
          icon: 'lucide:headset',
          title: 'Customer service',
          to: 'https://service.esw.com/',
          target: '_blank',
        },
        {
          icon: 'lucide:file-lock',
          title: 'Trust Centre',
          to: 'https://trust.esw.com/',
          target: '_blank',
        },
        {
          icon: 'lucide:globe-lock',
          title: 'Privacy Policy',
          to: 'https://esw.com/privacy-policy/',
          target: '_blank',
        },
      ],
    },
    toc: {
      enable: true,
      enableInMobile: false,
      enableInHomepage: false,
      title: 'On this page',
      links: [
        
      ],
      iconLinks: [
        
      ],
      carbonAds: {
        enable: false,
        disableInDev: true,
        disableInMobile: true,
        fallback: false,
        fallbackMessage: 'Please support us by disabling your ad blocker.',
        code: 'CW7ITKJN',
        placement: 'shadcn-docs-nuxtvercelapp',
        format: 'cover',
      },
    },
    search: {
      enable: true,
      inAside: false,
      style: 'input',
    },
    data: {},
  },
});
